---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing system dependencies..."
      - npm install -g npm@latest
  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - npm install -g @nestjs/cli
      - export PATH=$PATH:$(npm bin -g)
      - npm install
      - yum update -y
      - yum upgrade -y
      - yum install poppler-utils -y
      - echo "Pre-build completed."
  build:
    commands:
      - echo "Building the NestJS application..."
      - npm run build
      - echo "Build phase completed."
  post_build:
    commands:
      - echo "Post-build steps..."
      - echo "No post-build commands defined."
artifacts:
  files:
    - "**/*"
  base-directory: dist
