version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building the app..."
      - npm run build
artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"
