version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # Specify the Node.js version
    commands:
      - echo "Installing dependencies"
      - npm install -g @nestjs/cli
      - npm install

  build:
    commands:
      - echo "Building the application"
      - npm run build

artifacts:
  files:
    - nestjs-app.zip
    - "**/*"
  discard-paths: yes
