version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # Adjust the version to your app's requirements
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the NestJS application..."
      - npm run build # Compiles TypeScript to JavaScript
  post_build:
    commands:
      - echo "Packaging application for deployment..."
      - mkdir -p build
      - cp -R .ebextensions dist package.json package-lock.json Procfile build/
      - cd build
      - zip -r ../app.zip . # Package everything for Elastic Beanstalk
artifacts:
  files:
    - app.zip
